title: Bernhard Studios Webpage
author: Bernardo
email: bernardo.unity.2020@gmail.com
description: This is meant to be the main webpage of Bernhard Studios. Here we will post the link to all my social profiles as well as the download link for the apps we have developed.

# social links
twitter_username: BernhardStudios # DO NOT include the @ character, or else the build will fail!
github_username:  BernhardStudios # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
