title: Bernhard Studios
author: Bernardo M.
email: bernardo.unity.2020@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bernhard Studios are the developers of Night Fight. An indie platform based game available on the Play Store and coming soon to the App Store. Night Fight has been made using Unity and Blender.
  
theme: minima

# social links
twitter_username: BernhardStudios # DO NOT include the @ character, or else the build will fail!
github_username:  BernhardStudios # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
